---
- name: "Install docker & molecule"
  hosts: molecule
  become: true

  pre_tasks:
  - import_tasks: pre_tasks.yml

  roles:
  - role: geerlingguy.repo-epel

  post_tasks:
  - import_tasks: post_tasks.yml

